apiVersion: v1
kind: Pod
metadata:
  name: demo-app-pod
  namespace: VAR_NAMESPACE
  labels:
    author: VAR_NAMESPACE
spec:
  containers:
  - name: demo-app
    image: radowan/demo-app
    ports:
      - containerPort: 8080
    env:
      - name: RESPONSE
        value: "'Train yourself to let go of everything you fear to lose.' Y.'"